### ISSUE TITLE
Asterisk Emoji and some symbol are missing

### ISSUE THREAD

**Issue by afief** [sweaver2112/Regex-combined-emojis#2]
this asterisk emoji *️⃣  and some other symbol from https://getemoji.com/ are not detected
```
✢ ✣ ✤ ✥ ✦ ✧ ☆ ✯ ✩ ✪ ✫ ✬ ✭ ✮ ✶ ✷ ✵ ✸ ✹ → ⇒ ⟹ ⇨ ⇾ ➾ ⇢ ➔ ➜ ➙ ➛ ➝ ➞ ⚈ ⚉ ⚆ ⚇ 𓀀 𓀁 𓀂 𓀃 𓀄 𓀅 𓀆 𓀇 𓀈 𓀉 𓀊 𓀋 𓀌 𓀍 𓀎 𓀏 𓀐 𓀑 𓀒 𓀓 𓀔 𓀕 𓀖 𓀗 𓀘 𓀙 𓀚 𓀛 𓀜 𓀝
```
or is it intentional?

**Comment by sweaver2112** [comment]
The [Keycap Asterisk Emoji, "*️⃣",  was missing from the compact version due to regex errors, but is now present (asterisk not escaped).  The other pictographs on your list don't appear on Unicode.org's lists which is what the regex is built from (Egyptian Hieroglyphs are very cool but they aren't necessarily emojis)
